#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
bash run.sh 

## uncommont the next line to test part_seg
bash part_seg/run.sh 

# The previous version of this file was commented-out and follows below:
# 
# bash ldgcnn-master/run.sh 
# 
