#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.

python -u "NewData_ML_Kfold.py"
for file in fig_*.py; do
python -u "$file" &
done
wait


