#!/usr/bin/env bash
set -ex
export PYTHONWARNINGS="ignore"

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python -u Super-Iterative.py