#!/usr/bin/env bash
curl -L -O https://github.com/bprodoehl/phantomjs/releases/download/v2.0.0-20150528/phantomjs-2.0.0-20150528-u1404-x86_64.zip && \ unzip phantomjs-2.0.0-20150528-u1404-x86_64.zip && \ mv phantomjs-0.0.0-20150528 /root/bin
set -e
