#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
Rscript -e "rmarkdown::render(input = 'dp_survival.Rmd', output_dir = '../results', clean = TRUE)"
python -u correlation.py "$@"

